---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ptp
  namespace: default
spec:
  chart:
    spec:
      chart: ./ptp/
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: radisys-helm-repo
  interval: 1m0s
