---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: radisys-helm-repo
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/AWS-Demo-User/eks-a-workload-gitops/tree/main/HPE-lab-sn-36-workload-cluster/workload
