apiVersion: batch/v1
kind: Job
metadata:
  name: pre-requisite-job
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: pre-requisite
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "/scripts/pre-requisite.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: scripts
        configMap:
          name: pre-requisite-script
