---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: radisys-helm-repo
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/AWS-Demo-User/radisys-helm-repo/U37
  secretRef:
    name: private-repo-credentials

