   apiVersion: helm.toolkit.fluxcd.io/v2beta1
   kind: HelmRelease
   metadata:
     name: prometheus
     namespace: monitoring
   spec:
     interval: 5m
     chart:
       spec:
         chart: prometheus
         sourceRef:
           kind: HelmRepository
           name: prometheus
           namespace: flux-system
     values:
       alertmanager:
         enabled: true
       server:
         enabled: true
       pushgateway:
         enabled: true
       nodeExporter:
         enabled: true
